### PR TITLE
engines: add google lucky search

### PR DESCRIPTION
**Pull request by nikitavoloboev**

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Not sure if I need to change anything else. I just search and replaced the query so its the one referenced in #16. 

Although entering below in my browser tab search and pressing return

`https://www.google.com/search?btnI=I%27m+Feeling+Lucky&q=youtube&hl=ach&safe=off`

Doesnt actually do google lucky search.

**Comment by deanishe** [comment]
> Not sure if I need to change anything else

I see you've just noticed it needs a different name to the existing Google search.

You also need to add an icon in `src/icons/engines`.

**Comment by nikitavoloboev** [comment]
I wanted to squash them into 1 commit for cleaner history. Sorry.

**Comment by deanishe** [comment]
Doesn't matter.

You only renamed the engine, not the searches. When you add a search, it shows up as "Google (XYZ)", not "Google Lucky (XYZ)".

Can you please test stuff properly before submitting a PR?

**Comment by nikitavoloboev** [comment]
> Can you please test stuff properly before submitting a PR?

Didn't see this commit https://github.com/deanishe/alfred-searchio/commit/54b120a0ab68dbd54390b7dc879f181ba05225d8

Will do next time.

**Comment by deanishe** [comment]
What do you mean? That commit should be irrelevant to the PR.

See `google-lucky.json` in fff4aa4f0 to see the problem.

**Comment by nikitavoloboev** [comment]
> What do you mean?

Well I couldn't build the workflow to test it.

**Comment by nikitavoloboev** [comment]
I know I could of spotted it without building the workflow. Was just excited for @deanishe to have my PR merged. 😭

**Comment by nikitavoloboev** [comment]
A bit out of topic but I recently started using TaskPaper to disect problems I am trying to solve. Feel like a different human being now. I know you use it too so thought I'd mention it.

**Comment by deanishe** [comment]
> I know I could of spotted it without building the workflow

Yup, but you noticed that (and that the engine name needed changing), which is the main thing :+1:

> I recently started using TaskPaper to disect problems I am trying to solve

Out of interest, why? I thought you were a mindmaps guy.

I mostly use TaskPaper because I've never really got used to mindmaps, even though both are essentially just trees.

**Comment by nikitavoloboev** [comment]
> thought you were a mindmaps guy

I moved mainly because with MindNode, if I was to create a new node, I could not 'Focus in' on it. Unless I zoom out to some secluded part in a mind map. So I only see the main node and the branches. 

But now that I tried TaskPaper, it really is incredible. Ability to create projects. Nest as much as I like. Jump between projects with ease. It just flows a lot better and I only just started using it. 

I use mind maps for things like this now:



Drawing connections between things. A digital whiteboard. For example mapping the architecture of Learn Anything or some workflow would be nice to do in a visual mind map way. But otherwise TaskPaper is just too good. I am also moving my huge Trello board of things I want to learn (https://trello.com/b/cu32qF3q) to it because I need nesting.

So I can do things things like this: 

2018-10-02 at 20 34

But on multiple nest level. It's pretty awesome.

**Comment by nikitavoloboev** [comment]
Here is my approach to solving problems written out (https://wiki.nikitavoloboev.xyz/research/solving-problems.html). I try to be methodical with everything I do and build processes because I hate thinking.

**Pull request merged**
