### PR TITLE
Added icon to Google Lucky Search

### PR DESCRIPTION
**Pull request by nikitavoloboev**

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
I also added a Script filter `gl` for it as it was missing.

**Comment by deanishe** [comment]
- The Script Filter wasn't missing, it was deliberately not included by default.
- The icon is a duplicate of the normal Google icon, so it's pointless.
- You've broken Alfred 2 support, by editing the workflow in Alfred 3.

Please stop making PRs that are counter to the purpose of the workflow and/or break it.

**Comment by nikitavoloboev** [comment]
Curious why would you accept a PR to accept Google Lucky search support but not include it afterwards. Most users would never know it existed.

I added the icon because without that icon the script filter `items` had no icon.

Didn't know about the Alfred 2 compatibility.

I will stop making PRs to your repos. You are right. There is always something wrong that happens or I don't account for. Thank you for looking at it at least.

**Comment by nikitavoloboev** [comment]
Your pre release of Searchio is amazing. Thank you a lot for updating it.

**Comment by deanishe** [comment]
> Curious why would you accept a PR to accept Google Lucky search support but not include it afterwards.

Because I uninstalled Alfred 2 a long time ago (as it causes some issues when 2 & 3 are both installed), so I can't add new Script Filters without breaking the workflow…

I should have added it to the README, though. Same for Kinopoisk.

> I added the icon because without that icon the script filter items had no icon.

That icon goes in the workflow root directory. There was no need to add another Google icon in the `icons` directory.

> Forgot about the Alfred 2 compatibility. Do people still use it?

Sure. I don't know how many, but there are still some around. In any case, I don't like to break backwards-compatibility unless it's necessary. "I edited the workflow in Alfred 3" isn't a particularly good justification.

In the case of this workflow, the plan has always been to leave v1 for Alfred 2 and have v2 use Alfred 3's funky new features.

> I will stop making PRs to your repos.

No need to do that, but please think about your PRs a bit more first.

I haven't added "I'm feeling lucky" to v2 yet, so you could add that. That one *will* need a new icon, as they're based on the engine ID.

**Pull request closed without merging**
