### PR TITLE
Added external triggers to all script filters

### PR DESCRIPTION
**Pull request by nikitavoloboev**
Please consider accepting this pull request. It adds external triggers to all the script filters for people who prefer calling these script filters from external triggers.

2017-09-26 at 23 12

I have modified the info.plist file with all the changes I have made. And [here](https://transfer.sh/POfuc/Searchio-.alfredworkflow) is the workflow download. I hope you do consider adding them. 

Thank you.

### CODE REVIEW

**Comment by deanishe** [comment]
Why? What purpose do they serve?

(Also, the JSON Configs are entirely unnecessary. All they do is set `{query}` to `{query}`.)

**Comment by nikitavoloboev** [comment]
The purpose is for users who call these script filters from external triggers. Currently they will have to create the external triggers themselves and on next update duplicate workflow, then update, then transfer external triggers to the update. 

And the JSON configs serve the purpose of stripping title and subtext so when you call them you get a clean prompt.

**Comment by deanishe** [comment]
> The purpose is for users who call these script filters from external triggers

Obviously. I mean, why would anyone want to call the workflow via an External Trigger?

The workflow is intended to be edited by the user (to change the searches to their preferred engines and languages). Adding a bunch of External Triggers makes that more complicated to do, so I'm not going to add them if the use case is because one person doesn't like using keywords.

> stripping title and subtext so when you call them you get a clean prompt.

Ah right. Yeah. I forgot about the tiny flicker.

Updating this workflow requires the user to re-create all of their customised searches, which is a PITA, so I'm always reluctant to push updates. I will not do so to add features that are only of interest to one user, nor one day after a previous update.

I suggest you create an issue requesting the addition of External Triggers instead. If there is sufficient interest, I will consider adding them. If it's only you, well you can edit your own copy/fork.

**Comment by nikitavoloboev** [comment]
> Obviously. I mean, why would anyone want to call the workflow via an External Trigger?

[Karabiner](https://github.com/tekezo/Karabiner-Elements) provides a much easier way to call workflows, keyboard maestro macros or anything else as it gives you the ability to call applescript or shell commands and assign that directly to a key you like. 

I take great use of this feature as you can see [here](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml) and my personal documentation map for all the bindings I have [here](https://my.mindnode.com/c7EmmKvaxCyCEuTzcpkGB4MGeLpWdR8nsJK4rjDh).

> Adding a bunch of External Triggers makes that more complicated to do, so I'm not going to add them if the use case is because one person doesn't like using keywords.

I agree with you there. Sadly it seems I am the only person who is abusing Karabiner in this way. 😞

In any way, I hope Andrew adds [this](https://www.alfredforum.com/topic/10763-add-option-to-duplicate-and-update/?tab=comments#comment-55304). Because updating workflows is often a real pain, especially with Searchio, since I use so many of the script filters from it.

**Pull request closed without merging**
